#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

SITE_URL="${SITE_URL:-https://indiecraft-ten.vercel.app}"
PROD_CALLBACK="$SITE_URL/api/auth/x/callback"
LOCAL_CALLBACK="http://localhost:3000/api/auth/x/callback"

# vercel_env NAME VALUE — upsert a production environment variable.
# `env add` refuses to overwrite, so an existing value is removed first; the
# removal is allowed to fail because on a first run there is nothing to remove.
vercel_env() {
  local name="$1" value="$2"
  npx --yes vercel env rm "$name" production --yes >/dev/null 2>&1 || true
  if printf '%s' "$value" | npx --yes vercel env add "$name" production >/dev/null 2>&1; then
    printf '  %s✓ set%s Vercel production var %s\n' "$GREEN" "$RESET" "$name"
  else
    SKIPPED+=("Vercel var $name (npx vercel env add $name production)")
    warn "could not set $name on Vercel — are you logged in? (npx vercel login)"
  fi
}

banner "Indiecraft — X sign-in"

# ──────────────────────────────────────────────────────────────────────────
stage "Create the X app"
say "Claiming a sheet needs X to confirm that @someone is @someone."
say "That takes one OAuth app, which only you can create."
note "A free X developer account is enough. No paid tier, no API quota is used:"
note "we call /2/users/me once per sign-in and read the username."
open_url "https://developer.x.com/en/portal/dashboard"
step "Sign in as the account that should own the app."
step "Create a PROJECT first — any name, e.g. 'Indiecraft'."
step "Then create the App INSIDE that project."
warn "The app must belong to a Project. An app under 'Standalone Apps' will"
warn "  complete the whole OAuth flow, issue a valid token, and then have every"
warn "  v2 request refused with 403 client-not-enrolled — so sign-in fails with"
warn "  no hint as to why. If you already have a standalone app, attach it to a"
warn "  project rather than making a new one: the credentials stay the same."
step "Name it 'Indiecraft' (names are global, so add a suffix if it is taken)."
step "When it shows API Key / API Secret / Bearer Token, ignore all three —"
step "  those are OAuth 1.0a and this app does not use them."
pause "Done? Press Enter."

# ──────────────────────────────────────────────────────────────────────────
stage "Turn on OAuth 2.0 and set the callbacks"
say "This is the stage that decides whether sign-in works at all."
open_url "https://developer.x.com/en/portal/dashboard"
step "Open your app → 'User authentication settings' → Set up."
step "App permissions: 'Read' is enough."
step "Type of App: choose 'Web App, Automated App or Bot' (a confidential"
step "  client). This is what makes X issue a Client Secret — a 'Native App'"
step "  gets none, and the sign-in will fail at the token exchange."
say ""
step "Callback URI / Redirect URL — add BOTH of these, exactly:"
printf '      %s%s%s\n' "$BOLD" "$PROD_CALLBACK" "$RESET"
printf '      %s%s%s\n' "$BOLD" "$LOCAL_CALLBACK" "$RESET"
note "X matches these character for character. A trailing slash is a different URL."
step "Website URL: $SITE_URL"
step "Save."
pause "Saved? Press Enter."

# ──────────────────────────────────────────────────────────────────────────
stage "Copy the OAuth 2.0 credentials"
say "Saving those settings shows the Client ID and Client Secret once."
warn "The secret is shown ONCE. If this screen is gone, use Regenerate."
step "Copy the OAuth 2.0 Client ID."
ask X_CLIENT_ID "Paste the Client ID:"
step "Copy the OAuth 2.0 Client Secret."
ask_secret X_CLIENT_SECRET "Paste the Client Secret (hidden):"

if [[ -z "$X_CLIENT_ID" || -z "$X_CLIENT_SECRET" ]]; then
  warn "Both values are required — re-run when you have them."
  exit 1
fi

write_env X_CLIENT_ID "$X_CLIENT_ID"
write_env X_CLIENT_SECRET "$X_CLIENT_SECRET"

# ──────────────────────────────────────────────────────────────────────────
stage "Generate the session signing secret"
say "AUTH_SECRET signs the cookie that says who you are. Nobody types this one."
note "Without it the app falls back to CRON_SECRET, which works but reuses a"
note "secret that already has another job. A separate value is cheap."
AUTH_SECRET=$(_existing AUTH_SECRET || true)
if [[ -n "$AUTH_SECRET" ]]; then
  say "An AUTH_SECRET already exists in $ENV_FILE — keeping it."
  note "Replacing it would sign everybody out, which is harmless but pointless."
else
  AUTH_SECRET=$(openssl rand -base64 32 2>/dev/null || head -c 32 /dev/urandom | base64)
  say "Generated 32 random bytes."
fi
write_env AUTH_SECRET "$AUTH_SECRET"

# ──────────────────────────────────────────────────────────────────────────
stage "Send the three values to Vercel"
say "Production reads these from Vercel, not from your .env."
note "GitHub Actions does NOT need them: the nightly crawler never signs anyone in."
if confirm "Write X_CLIENT_ID, X_CLIENT_SECRET and AUTH_SECRET to Vercel production?"; then
  vercel_env X_CLIENT_ID "$X_CLIENT_ID"
  vercel_env X_CLIENT_SECRET "$X_CLIENT_SECRET"
  vercel_env AUTH_SECRET "$AUTH_SECRET"
else
  SKIPPED+=("Vercel production vars X_CLIENT_ID, X_CLIENT_SECRET, AUTH_SECRET")
  warn "skipped — claiming stays switched off in production until these are set"
fi

# ──────────────────────────────────────────────────────────────────────────
stage "Deploy and check"
say "Environment variables only reach the app on the next deploy."
if confirm "Deploy to production now?"; then
  npx --yes vercel --prod --yes >/dev/null 2>&1 \
    && printf '  %s✓ deployed%s\n' "$GREEN" "$RESET" \
    || warn "deploy failed — run 'npx vercel --prod' and read the output"
  sleep 8
  code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 30 "$SITE_URL/api/auth/x/start" || echo 000)
  if [[ "$code" == "302" || "$code" == "307" ]]; then
    printf '  %s✓ sign-in is live%s (/api/auth/x/start redirects to X)\n' "$GREEN" "$RESET"
  elif [[ "$code" == "404" ]]; then
    warn "/api/auth/x/start still returns 404 — the credentials did not reach this deploy"
  else
    warn "/api/auth/x/start returned $code — check the Vercel logs"
  fi
else
  SKIPPED+=("deploy (npx vercel --prod)")
fi

say ""
say "Then, to prove the whole loop end to end:"
step "Open $SITE_URL/c/<your-handle> and click 'This is me — claim this sheet'."
step "After claiming, the page drops its noindex and joins $SITE_URL/sitemap.xml."

finish
